version: "3.7"

services:
  mongo:
    image: mongo:4.0
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app/
    depends_on:
      - mongo
